server:
  port: 8080

spring:
  application:
    name: resource-test-server
  security:
    oauth2:
      resourceserver: # oAuth2 ????? ? ??? ??? ??
        jwt:
          issuer-uri: http://auth.sesac-univ.click
