server:
  port: 9000

spring:
  # 1. LDAP 연결에 필요한 정보들을 Property 에 저장하고 주입하기 (CoP, Configuration of Properties)
  ldap: # -> 이 내용들은 LdapContextSource 클래스에 주입된다. (LDAP Init 과 관련된 기본 클래스)
    # LDAP 서버의 주소을 지정. 여러 서버가 있다면 쉽표(,)로 다중 서버 연결 지원
    urls: ldap://3.36.117.133:389
    # LDAP 디렉터리에서 검색할 기본 DN(Base Distinguished Name)
    base: dc=sesac-univ,dc=click
    # 관리자 계정 - bind 방식으로 서버에 연결될 때 읽기/쓰기 권한이 부여된 계정
    username: cn=admin,dc=sesac-univ,dc=click
    password: 1q2w#E$R

  application:
    name: auth-test-srv
  security:
    oauth2:
      authorization-server:
        client:
         sesac-univ:
            registration:
              client-id: sesac-univ
              client-secret: '{noop}secret'
              client-name: Articles Client
              client-authentication-methods:
                - client_secret_post
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - password
              redirect-uris: http://sesac-univ.click/auth/callback
              scopes:
                - openid
                - articles.read
        issuer: http://auth.sesac-univ.click
        endpoint:
          token-uri: /oauth2/token
          authorization-uri: /oauth2/authorize
  web:
    resources:
      cache:
        period: 0
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE